# Generated by Django 5.2.7 on 2025-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
