# Generated by Django 5.2.7 on 2025-11-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_usersession_role_alter_usersession_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
